version: "3"
services:
  traefik:
    image: traefik:1.7.4
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "81:80"
      - "8080:8080"
      #- "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    networks:
      - webgateway
 
networks:
  webgateway:
    driver: bridge